apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-a913b6d2-1d26-4306-9b1d-979363214711
  name: devfile-sample
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample
status:
  loadBalancer: {}
