apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-a913b6d2-1d26-4306-9b1d-979363214711
  name: devfile-sampleibwo
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample
    weight: null
status: {}
